repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    # -   id: check-added-large-files # prevents giant files from being committed.
    -   id: check-ast # simply checks whether the files parse as valid python.
    -   id: check-case-conflict # checks for files that would conflict in case-insensitive filesystems.
    -   id: check-json # checks json files for parseable syntax.
    -   id: check-toml # checks toml files for parseable syntax.
    -   id: check-xml # checks xml files for parseable syntax.
    -   id: check-yaml # checks yaml files for parseable syntax.
    -   id: detect-private-key # detects the presence of private keys.

- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.0.282
  hooks:
    - id: ruff # configuration in pyproject.toml file