# Generated by Django 4.2.7 on 2023-12-03 15:27

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('event_id', models.TextField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('event_name', models.TextField(unique=True)),
                ('event_start_date', models.DateTimeField(null=True)),
                ('event_end_date', models.DateTimeField(null=True)),
                ('event_created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='EventExpenseItem',
            fields=[
                ('event_expense_item_id', models.TextField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('event_expense_item_name', models.TextField()),
                ('event_expense_item_price_eur', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('participant_id', models.TextField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('participant_email', models.EmailField(max_length=254, unique=True)),
                ('participant_first_name', models.TextField()),
                ('participant_last_name', models.TextField()),
                ('participant_created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='EventParticipant',
            fields=[
                ('event_participant_id', models.TextField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('event_participant_registered_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='group_expense_tracker_app.event')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='group_expense_tracker_app.participant')),
            ],
        ),
        migrations.CreateModel(
            name='EventExpenseGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_expense_group_id', models.TextField(editable=False)),
                ('paid_eur', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('event_expense_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='group_expense_tracker_app.eventexpenseitem')),
                ('event_participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='group_expense_tracker_app.eventparticipant')),
            ],
        ),
    ]
