# Generated by Django 4.2.7 on 2023-12-25 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('group_expense_tracker_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventExpenseGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paid_eur', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('event_participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='group_expense_tracker_app.eventparticipant')),
            ],
        ),
        migrations.CreateModel(
            name='EventExpenseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('price_eur', models.DecimalField(decimal_places=2, max_digits=10)),
                ('event_expense_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='group_expense_tracker_app.eventexpensegroup')),
            ],
        ),
    ]
