# Generated by Django 4.2.7 on 2023-11-30 00:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('group_expense_tracker_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('event_id', models.TextField(primary_key=True, serialize=False, unique=True)),
                ('event_name', models.TextField()),
                ('event_start_date', models.DateTimeField(null=True)),
                ('event_end_date', models.DateTimeField(null=True)),
                ('event_created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='EventExpenseGroup',
            fields=[
                ('event_expense_group_id', models.TextField(primary_key=True, serialize=False, unique=True)),
                ('paid_eur', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='EventExpenseItem',
            fields=[
                ('event_expense_item_id', models.TextField(primary_key=True, serialize=False, unique=True)),
                ('event_expense_item_name', models.TextField()),
                ('event_expense_item_price_eur', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='EventParticipant',
            fields=[
                ('event_participant_id', models.TextField(primary_key=True, serialize=False, unique=True)),
                ('event_participant_registered_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='group_expense_tracker_app.event')),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('participant_id', models.TextField(primary_key=True, serialize=False, unique=True)),
                ('participant_email', models.EmailField(max_length=254, unique=True)),
                ('participant_created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Posts',
        ),
        migrations.AddField(
            model_name='eventparticipant',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='group_expense_tracker_app.participant'),
        ),
        migrations.AddField(
            model_name='eventexpensegroup',
            name='event_expense_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='group_expense_tracker_app.eventexpenseitem'),
        ),
        migrations.AddField(
            model_name='eventexpensegroup',
            name='event_participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='group_expense_tracker_app.eventparticipant'),
        ),
    ]
