# Generated by Django 4.2.7 on 2023-12-29 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('group_expense_tracker_app', '0002_alter_eventexpensegroup_event_participant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventexpensegroup',
            name='event_participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='group_expense_tracker_app.eventparticipant'),
        ),
        migrations.AlterField(
            model_name='eventparticipant',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='group_expense_tracker_app.event'),
        ),
        migrations.AlterField(
            model_name='eventparticipant',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='group_expense_tracker_app.participant'),
        ),
    ]
