# Generated by Django 4.2.7 on 2023-12-02 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group_expense_tracker_app', '0003_alter_event_event_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
