# Generated by Django 4.2.7 on 2023-12-31 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group_expense_tracker_app', '0003_alter_eventexpensegroup_event_participant_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventDataView2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.IntegerField()),
                ('event_name', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('created_at', models.DateTimeField()),
                ('view_id', models.IntegerField()),
                ('item_name', models.CharField(max_length=255)),
                ('item_id', models.IntegerField()),
                ('participant_id', models.IntegerField()),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'get_event_data_view2',
                'managed': False,
            },
        ),
    ]
