# Generated by Django 4.2.7 on 2023-12-02 13:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('group_expense_tracker_app', '0005_alter_event_event_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventexpensegroup',
            name='event_expense_group_id',
            field=models.TextField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='eventexpenseitem',
            name='event_expense_item_id',
            field=models.TextField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='eventparticipant',
            name='event_participant_id',
            field=models.TextField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='participant',
            name='participant_id',
            field=models.TextField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
