# Generated by Django 4.2.7 on 2023-12-03 08:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('group_expense_tracker_app', '0007_alter_event_event_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='participant_first_name',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='participant',
            name='participant_last_name',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
